# Run on Docker.com
# FROM java:8

# Run on daocloud
FROM daocloud.io/library/java:openjdk-8u40-b22
MAINTAINER downgoon@qq.com
COPY target/springboot-docker-hello-world-0.1.0.jar hello-world.jar
CMD ["java", "-jar", "hello-world.jar"]
